### ISSUE TITLE
View Creator not working

### ISSUE THREAD

**Issue by Frederik91** [WeConnect/case-apps#10]
Hello

It seems to be an issue with the View Creator. When starting the function the following message appears: 

> [Main Instruction]
> Failed to initialize the add-in “View
> Creator” because the class "Case.ViewCreator.Entry.CmdMain" cannot be found in the add-in assembly.
> The FullClassName provides the entry point for Revit to call the add-in application. For Revit to run the add-in, you must ensure this class implements the "Autodesk.Revit.UI.IExternalCommand" interface.

This issue can be reproduced by clicking the "View Creator" button. 

The error has been reproduced on both Revit 2016 and Revit 2017.

**Comment by Frederik91** [comment]
After looking at the code I realize that this function is made for Revit 2013. Will this function be updated for future Revit versions?

**Comment by DuncanLithgow** [comment]
I'm seeing this as well. Do we have anyone active able to look at this? @Frederik91 do you have any coding experience?

**Comment by sixtysecondrevit** [comment]
@DuncanLithgow @Frederik91 , [PR#22](https://github.com/WeConnect/case-apps/pull/22) fixes this issue. I revised the namespace name so it can properly run. cc @rudderdon

**Comment by sixtysecondrevit** [comment]
![20171101-viewcreatorfix](https://user-images.githubusercontent.com/15744724/32286171-33893d02-bef2-11e7-8d73-2a5f780d37a5.gif)

**Comment by sixtysecondrevit** [comment]
Fixed with this commit https://github.com/WeConnect/case-apps/commit/6827f94fa85e0414b4d8b1f435993a0723ef7427

@kmorin , @rudderdon - Can we close this issue?
