### ISSUE TITLE
Change/Replace Line Styles tool appears twice

### ISSUE THREAD

**Issue by DuncanLithgow** [WeConnect/case-apps#12]
The Change/Replace Line Styles tool appears both in the Apps#1 and Apps#2 set. Hardly important, but should be fixed never-the-less.

**Comment by kmorin** [comment]
same as #13

**Comment by DuncanLithgow** [comment]
Do we need to go through all the tools looking for duplicate functionality? Does this mean that there are duplicate code sections behind the UI?
