### ISSUE TITLE
Usage documentation 

### ISSUE THREAD

**Issue by DuncanLithgow** [WeConnect/case-apps#7]
I just wanted to start a discussion about documentation for the plugins. @rudderdon mentioned in #5 that "All documentation is gone and won't come back unless the community provides it."

Is there an old PDF somewhere kicking around?

What is available to build on?

**Comment by rudderdon** [comment]
There is nothing floating around. The only documentation that really existed was on the original case apps web site and that was removed last year. No backups exists for that site.

**Comment by Robbo1234** [comment]
Hi Duncan/Don

David Light formerly of CASE Apps uploaded these two useful tutorials on Exceler8 Export Categories . Refer to links below:

A demonstration of the CASE pro app exceler 8 tool to modify Revit Mass Heights
[https://www.youtube.com/watch?v=MHrpQ52w2C8](url)
 
This video shows the exporting process of Revit data to excel via exceler8, then linking this data into another excel spreadsheet. Update the model & export the data again to ensure you always have the most up to-date data.

[https://www.youtube.com/watch?v=6RYdEzkMBZc](url)

Also this video shows exceler8 Export Schedules in action:
https://www.youtube.com/watch?v=mCGliXFp31Y

Regards

Rob

**Comment by Robbo1234** [comment]
Also refer to [http://revitaddons.blogspot.ie/search?q=Case+Apps](url)

**Comment by Robbo1234** [comment]
Also refer to http://revitaddons.blogspot.ie/search?q=Case+Apps

**Comment by DuncanLithgow** [comment]
Would it be a good idea to enable (?) the wiki for this project so we can start documentation? For now just a place to collect useful links and articles...

**Comment by AV4TAr** [comment]
@DuncanLithgow that's a good idea.

**Comment by Robbo1234** [comment]
@DuncanLithgow sounds like a plan, btw is there a workflow to install the Apps Set #3 which were not included in the installer? Thanks

**Comment by DuncanLithgow** [comment]
Glad some people like the idea!

@Robbo1234 discussion about Apps Set 3 shout be kept in issue #5

**Comment by DuncanLithgow** [comment]
I don't remember why this issue was closed, but I'd like to open it again.

As yet we have no place to make documentation. Can someone here activate the wiki section of this project?

**Comment by DuncanLithgow** [comment]
Could someone enable the wiki section of this project so I can write a bit of documentation?
